# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
import subprocess
import webbrowser

def chrome_launch(url: str) -> bool:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import subprocess
import webbrowser