# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json
import py_compile
import subprocess
import sys
import traceback

def run_in_sandbox(tool_name: str, test_params: dict) -> tuple[bool, str]:
    ...

def auto_programmer(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import sys
import py_compile
import subprocess
import traceback
import pathlib
import os
import ast
import threading