# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import os
import pyautogui
import pyperclip
import time

def computer_control(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import time
import pyautogui
import pyperclip