# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import os
import sys

def computer_settings(parameters: dict, response: Any, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import pyautogui
import ctypes
import comtypes
import comtypes.CoInitialize
import comtypes.CoUninitialize
import pycaw
import pycaw.pycaw
import pygetwindow