# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
import json
import sys

def get_base_dir() -> Path:
    ...

CONFIG_DIR = BASE_DIR / 'config'
CONFIG_FILE = CONFIG_DIR / 'api_keys.json'
def ensure_config_dir() -> None:
    ...

def config_exists() -> bool:
    ...

def is_configured() -> bool:
    ...

def load_api_keys() -> dict[str, str]:
    ...

def save_api_keys(keys: dict[str, str]) -> None:
    ...

def get_gemini_key() -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import json
import pathlib