# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from comtypes import CLSCTX_ALL
from ctypes import POINTER, cast
from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
from typing import Any
import psutil
import pygetwindow
import subprocess

def set_master_volume(volume_percent: int) -> bool:
    ...

def get_master_volume() -> int:
    ...

def set_brightness(percent: int) -> bool:
    ...

def set_power_plan(plan_name: str) -> bool:
    ...

def set_focus_assist(level: int) -> bool:
    ...

def contextual_control(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import subprocess
import pygetwindow
import psutil
import ctypes
import comtypes
import comtypes.CLSCTX_ALL
import pycaw
import pycaw.pycaw
import winreg