# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Any
import os

def document_creator(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import pathlib
import datetime
import ntpath
import docx
import openpyxl