# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import os
import shutil
import traceback

def resolve_path(p: str) -> str:
    ...

def file_controller(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import shutil
import traceback
import pathlib
import ntpath
import send2trash