# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json

BASE_DIR = Path(__file__).resolve().parent.parent
GOALS_PATH = BASE_DIR / 'config' / 'goals.json'
def goals(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import pathlib