# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
import json
import sys
import threading

def get_base_dir() -> Path:
    ...

MEMORY_PATH = BASE_DIR / 'memory' / 'long_term.json'
MAX_VALUE_LENGTH = 500
MEMORY_MAX_CHARS = 4000
def _empty_memory() -> dict:
    ...

def load_memory() -> dict:
    ...

def save_memory(memory: dict) -> None:
    ...

def _recursive_update(d: dict, u: dict) -> dict:
    ...

def _truncate_value(val: str) -> str:
    ...

def _all_entries(mem: dict) -> list[tuple[str, str, str]]:
    ...

def _trim_to_limit(mem: dict) -> dict:
    ...

def update_memory(updates: dict) -> None:
    ...

def remember(category: str, key: str, value: str) -> None:
    ...

def forget(category: str, key: str) -> None:
    ...

def forget_memory() -> None:
    ...

def format_memory_for_prompt(memory: dict) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import json
import threading
import pathlib