# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any

def morning_brief(parameters: dict, player: Any) -> str:
    ...

def already_briefed_today() -> bool:
    ...

def mark_briefed() -> None:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
