# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import os
import subprocess
import traceback
import webbrowser

def find_executable(app_name: str) -> str:
    ...

def open_app(parameters: dict, response: Any, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import subprocess
import webbrowser
import traceback
import ntpath