# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json
import os

RULES_PATH = Path(__file__).resolve().parent.parent / 'config' / 'rules.json'
def proactive_automation(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import os
import pathlib
import psutil