# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import threading
import time

def reminder(parameters: dict, response: Any, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import threading
import time
import winsound