# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json

BASE_DIR = Path(__file__).resolve().parent.parent
RULES_PATH = BASE_DIR / 'config' / 'rules.json'
def rules_engine(parameters: dict, player: Any) -> str:
    ...

def start_rules_runner(player: Any, speak: Any) -> None:
    ...

def _load_rules() -> list[dict]:
    ...

def check_phrase_triggers(text: str) -> list[dict]:
    ...

def _run_action(action: dict) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import pathlib