# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any

def scheduler(parameters: dict, player: Any, speak: Any) -> str:
    ...

def start_runner(player: Any, speak: Any) -> None:
    ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
