# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from PIL import Image
from mss import mss
from pathlib import Path
from typing import Any
import base64
import io
import json
import urllib.error
import urllib.request

def _get_api_key() -> str:
    ...

def _capture_screen_base64() -> str:
    ...

def screen_vision(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import base64
import urllib
import urllib.request
import urllib.error
import pathlib
import mss
import mss.mss
import PIL
import PIL.Image
import io