# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from pathlib import Path
from typing import Any
import difflib
import os
import shutil

JARVIS_ROOT = Path(__file__).resolve().parent.parent
BACKUP_DIR = JARVIS_ROOT / 'backups'
def _ensure_backup_dir() -> Any:
    ...

def _make_backup(file_path: Path) -> str:
    ...

def _resolve_path(file_ref: str) -> Path:
    ...

def self_edit(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import shutil
import difflib
import pathlib
import datetime