# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import psutil

def system_monitor(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import psutil