# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from actions.openrouter_agent import openrouter_agent
from datetime import datetime
from typing import Any
from typing_extensions import Self
import os
import threading
import time
import uuid

class TaskPriority:
class TaskQueue:
    def __init__(self: Self) -> None: ...
    def submit(self: Self, goal: str, priority: int, speak: Any) -> str: ...
    def _process_task(self: Self, goal: str, task_id: str, speak: Any) -> Any: ...

def get_queue() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import threading
import uuid
import time
import os
import datetime
import actions
import actions.openrouter_agent
import ntpath