# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import os
import subprocess

def terminal_agent(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import subprocess
import os