# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json
import os
import sys

def tool_creator(parameters: dict, player: Any, speak: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import os
import sys
import pathlib
import ast
import threading