# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json

BASE_DIR = Path(__file__).resolve().parent.parent
PROFILE_PATH = BASE_DIR / 'config' / 'user_profile.json'
def user_profile(parameters: dict, player: Any) -> str:
    ...

def _load_profile() -> dict:
    ...

def _save_profile(profile: dict) -> None:
    ...

def record_action(name: str, args: dict) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import pathlib