# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import base64
import io
import json
import re
import urllib.error
import urllib.request

BASE_DIR = Path(__file__).resolve().parent.parent
API_FILE = BASE_DIR / 'config' / 'api_keys.json'
def _get_api_key() -> str:
    ...

def visual_click(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import urllib
import urllib.request
import urllib.error
import base64
import io
import re
import pathlib
import mss
import pyautogui
import PIL
import PIL.Image