# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import json
import urllib.parse
import urllib.request

def weather_action(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import urllib
import urllib.request
import urllib.parse
import json