# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import re
import traceback
import urllib.parse
import urllib.request
import webbrowser

def web_navigation(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import urllib
import urllib.request
import urllib.parse
import re
import webbrowser
import traceback