# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any
import json
import pyautogui
import time
import urllib.parse
import webbrowser

pyautogui = None
BASE_DIR = Path(__file__).resolve().parent.parent
CONTACTS_FILE = BASE_DIR / 'config' / 'whatsapp_contacts.json'
def load_contacts() -> dict:
    ...

def save_contacts(contacts: dict) -> Any:
    ...

def whatsapp(parameters: dict, player: Any) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import time
import urllib
import urllib.parse
import webbrowser
import json
import pathlib
import pyautogui
import ctypes
import PIL
import PIL.Image
import io